version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: cryptoshield_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cryptoshield

  mongo-express:
    image: mongo-express:latest
    container_name: cryptoshield_mongo_ui
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: cryptoshield123
    depends_on:
      - mongodb

volumes:
  mongo_data:
